package com.tf.usermanagement.domain;
// Generated Aug 5, 2016 12:36:10 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserOrganizationRoleId generated by hbm2java
 */
@Embeddable
public class UserOrganizationRoleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long userId;
	private long roleId;
	private int organizationId;
	private Byte active;
	private Long createdBy;
	private Date createdDate;
	private Date modifiedDate;
	private Long modifiedBy;

	public UserOrganizationRoleId() {
	}

	public UserOrganizationRoleId(long userId, long roleId, int organizationId) {
		this.userId = userId;
		this.roleId = roleId;
		this.organizationId = organizationId;
	}

	public UserOrganizationRoleId(long userId, long roleId, int organizationId, Byte active, Long createdBy,
			Date createdDate, Date modifiedDate, Long modifiedBy) {
		this.userId = userId;
		this.roleId = roleId;
		this.organizationId = organizationId;
		this.active = active;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "ROLE_ID", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "ORGANIZATION_ID", nullable = false)
	public int getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(int organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "ACTIVE")
	public Byte getActive() {
		return this.active;
	}

	public void setActive(Byte active) {
		this.active = active;
	}

	@Column(name = "CREATED_BY")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CREATED_DATE", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "MODIFIED_DATE", length = 23)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "MODIFIED_BY")
	public Long getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(Long modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserOrganizationRoleId))
			return false;
		UserOrganizationRoleId castOther = (UserOrganizationRoleId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getRoleId() == castOther.getRoleId())
				&& (this.getOrganizationId() == castOther.getOrganizationId())
				&& ((this.getActive() == castOther.getActive()) || (this.getActive() != null
						&& castOther.getActive() != null && this.getActive().equals(castOther.getActive())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedDate() == castOther.getCreatedDate())
						|| (this.getCreatedDate() != null && castOther.getCreatedDate() != null
								&& this.getCreatedDate().equals(castOther.getCreatedDate())))
				&& ((this.getModifiedDate() == castOther.getModifiedDate())
						|| (this.getModifiedDate() != null && castOther.getModifiedDate() != null
								&& this.getModifiedDate().equals(castOther.getModifiedDate())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy())
						|| (this.getModifiedBy() != null && castOther.getModifiedBy() != null
								&& this.getModifiedBy().equals(castOther.getModifiedBy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getRoleId();
		result = 37 * result + this.getOrganizationId();
		result = 37 * result + (getActive() == null ? 0 : this.getActive().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode());
		result = 37 * result + (getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "UserOrganizationRoleId [userId=" + userId + ", roleId=" + roleId + ", organizationId=" + organizationId
				+ ", active=" + active + ", createdBy=" + createdBy + ", createdDate=" + createdDate + ", modifiedDate="
				+ modifiedDate + ", modifiedBy=" + modifiedBy + "]";
	}
	
	

}
