package com.tf.usermanagement.domain;
// Generated Aug 5, 2016 12:36:10 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserOrganizationRole generated by hbm2java
 */
@Entity
@Table(name = "USER_ORGANIZATION_ROLE")
public class UserOrganizationRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private UserOrganizationRoleId id;

	public UserOrganizationRole() {
	}

	public UserOrganizationRole(UserOrganizationRoleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false)),
			@AttributeOverride(name = "roleId", column = @Column(name = "ROLE_ID", nullable = false)),
			@AttributeOverride(name = "organizationId", column = @Column(name = "ORGANIZATION_ID", nullable = false)),
			@AttributeOverride(name = "active", column = @Column(name = "ACTIVE")),
			@AttributeOverride(name = "createdBy", column = @Column(name = "CREATED_BY")),
			@AttributeOverride(name = "createdDate", column = @Column(name = "CREATED_DATE", length = 23)),
			@AttributeOverride(name = "modifiedDate", column = @Column(name = "MODIFIED_DATE", length = 23)),
			@AttributeOverride(name = "modifiedBy", column = @Column(name = "MODIFIED_BY")) })
	public UserOrganizationRoleId getId() {
		return this.id;
	}

	public void setId(UserOrganizationRoleId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "UserOrganizationRole [id=" + id + "]";
	}
	
	

}
